id: product
type: researcher_ai
researcher_type: product
# Researcher AI Configuration: Product & Technology Intelligence
# Links to pom-core collection schema for data structure

collection_schema_id: Research_product
name: Research Product

researcher_identity:
  title: Product & Technology Intelligence Analyst
  mission: Analyze product portfolios, technology stacks, and technical capabilities
  ecosystem_role: Product-focused researcher delivering structured technology intelligence
  core_competencies:
  - 'Product Analysis: Portfolio mapping, product categories, maturity assessment'
  - 'Technology Stack: Technical capabilities, API documentation, platform integrations'
  - 'Feature Research: Specifications, capabilities, competitive positioning'
  - 'Technical Due Diligence: Technology assessment, platform evaluation, roadmap
    analysis'

# Semantic search queries for page selection (BM25/vector injectors)
# Issue #384: Multiple queries for comprehensive Page_facts coverage
search_queries:
  - "What are the main products and features offered?"
  - "What capabilities does the platform provide and how does it work?"
  - "What is the technology stack and platform integrations?"
  - "What pricing plans and tiers are available?"

# Focus areas for this researcher (guides LLM attention)
focus_areas:
  - Product type and category (what kind of product is this)
  - Core features and capabilities (what does it do)
  - Technology stack and platform architecture
  - Pricing model and tiers (subscription, usage-based, freemium)
  - Integration ecosystem and API capabilities

# Fact types to extract from source content
fact_types:
  - product_name
  - product_feature
  - technology_stack
  - pricing_model
  - integration
  - api_capability
  - platform_architecture

# Tools available for this researcher (AITools that can be called by the AI)
# NOTE: Tool format issue fixed in pom-core v3.0.28+ (execution_engine.py)
tools:
  - brave_search  # Web search for product news

tool_guidance:
  brave_search:
    priority: medium
    max_calls: 1  # LIMIT: Only 1 search - product info usually on website
    when_to_use: |
      🔍 SEARCH ONLY IF page content lacks product details
      
      **SEARCH (IF NEEDED): Product announcements**
      → "{company} product feature announcement"
      
      **DON'T SEARCH FOR:**
      - Basic product info (on website)
      - Feature lists (check docs)
      - Pricing (see pricing page)

# page_categories_of_interest: REMOVED - not implemented in pom-core (dead code)
