id: product
type: researcher_ai
researcher_type: product
# Researcher AI Configuration: Product & Technology Intelligence
# Links to pom-core collection schema for data structure

collection_schema_id: Research_product
name: Research Product

researcher_identity:
  title: Product & Technology Intelligence Analyst
  mission: Analyze product portfolios, technology stacks, and technical capabilities
  ecosystem_role: Product-focused researcher delivering structured technology intelligence
  core_competencies:
  - 'Product Analysis: Portfolio mapping, product categories, maturity assessment'
  - 'Technology Stack: Technical capabilities, API documentation, platform integrations'
  - 'Feature Research: Specifications, capabilities, competitive positioning'
  - 'Technical Due Diligence: Technology assessment, platform evaluation, roadmap
    analysis'
  - 'Go-to-Market Analysis: Sales motion, distribution strategy, customer acquisition'

# Semantic search queries for page selection (page_facts_vector injector)
# Issue #384: Multiple queries for comprehensive Page_facts coverage
# NOTE: Queries phrased as ANSWER DESCRIPTIONS, not questions
# Questions match question-like patterns in legal/boilerplate content
# Answer descriptions match actual product content
search_queries:
  - "product platform feature capability integration API"
  - "pricing plan tier subscription freemium enterprise"
  - "technology stack cloud native architecture scalable"
  - "demo trial free sign up get started request"

# BM25 keyword queries - used by page_facts_vector injector (supplements vector)
keyword_queries:
  - "integrations"
  - "api"
  - "documentation"
  - "pricing"
  - "free trial"
  - "demo"
  - "sdk"

# URL boost patterns - used by page_facts_vector injector
url_boost_patterns:
  - "/product"
  - "/platform"
  - "/features"
  - "/pricing"
  - "/docs"
  - "/api"
  - "/integrations"
  - "/solutions"

# Focus areas for this researcher (prompt guidance, not used by injector)
focus_areas:
  - Product type and category (what kind of product is this)
  - Core features and capabilities (what does it do)
  - Technology stack and platform architecture
  - Pricing model and tiers (subscription, usage-based, freemium)
  - Integration ecosystem and API capabilities
  - Go-to-market strategy (PLG, sales-led, partner-led, community-led)

# Fact types to extract from source content
# Used by ContextExecutor for fact-type prioritization when preparing context.
fact_types:
  - product_name
  - product_feature
  - technology_stack
  - pricing_model
  - integration
  - api_capability
  - platform_architecture
  - go_to_market

# Anti-patterns to avoid (guides LLM away from common mistakes)
avoid:
  - Listing competitor products (that's the competitor researcher's job)
  - Describing features not explicitly mentioned in source content
  - Confusing marketing claims with verified technical capabilities
  - Including deprecated or discontinued products without noting status
  - Speculating on technology stack without evidence
  - Mixing up pricing tiers or plans from different time periods
  - Guessing go-to-market strategy without evidence (use Unknown if unclear)

# Tools available for this researcher (AITools that can be called by the AI)
# NOTE: Tool format issue fixed in pom-core v3.0.28+ (execution_engine.py)
tools:
  - brave_search  # Web search for product news

tool_guidance:
  brave_search:
    priority: medium
    max_calls: 1  # LIMIT: Only 1 search - product info usually on website
    when_to_use: |
      🔍 SEARCH ONLY IF page content lacks product details

      **SEARCH (IF NEEDED): Product announcements**
      → "{company} product feature announcement"

      **DON'T SEARCH FOR:**
      - Basic product info (on website)
      - Feature lists (check docs)
      - Pricing (see pricing page)
# page_categories_of_interest: REMOVED - not implemented in pom-core (dead code)

citation_note: "No inline URLs in field values; put sources in CIT/evidence fields."

# Post-execution tools for this researcher
# Run in priority order after main LLM completes
post_execution_tools:
  - parallel_array_enricher  # Priority 10: Fill post fields (productCategories, productPricing, productFeatures, scores per product)
  - enum_cat                 # Priority 30: Classify EnumCat fields (productDomain, technologyStackCat, pricingModelCat, etc.)
  - vec_cat                  # Priority 40: Classify VecCat fields (productTypeCat)
